In [2]:
from bs4 import BeautifulSoup as soup
from urllib.request import urlopen as uReq
import pandas as pd

my_url = 'https://www.flipkart.com/search?q=iphone&marketplace=FLIPKART&otracker=start&as-show=on&as=off'

uClient = uReq(my_url)
page_html = uClient.read()
uClient.close()
page_soup = soup(page_html, "html.parser")

containers = page_soup.findAll("div", {"class" : "_3O0U0u"})
#print(len(containers))

#print(soup.prettify(containers[0]))


container = containers[0]
#print(container.div.img["alt"])

#for showing the price
price = container.findAll("div", {"class" : "col col-5-12 _2o7WAb"})
#print(price[0].text)


#for rating
rating = container.findAll("div", {"class" : "niH0FQ"})
#print(rating[0].text)


#for creating a csv file for storing the data in a file
filename = "product.csv"
f = open(filename,"w")

headers = "Products_name , Pricing , Rating\n"
f.write(headers)


for container in containers:
    product_name = container.div.img["alt"]
    
    price = container.findAll("div", {"class" : "col col-5-12 _2o7WAb"})
    #here strip will eliminate unnaccessory data like(,.\etc)
    price = price[0].text.strip()
    
    rating = container.findAll("div", {"class" : "niH0FQ"})
    rating = rating[0].text
    
    
    #print ("product_name:"+product_name)
    #print("price : "+price)
    #print ("Rating :" +rating)
    
    #String passing for removing extra data
    #price=trim_price
    trim_price = ''.join(price.split(','))
    rm_rupee = trim_price.split("₹")
    add_rs_price = "Rs." + rm_rupee[1]
    split_price = add_rs_price.split('E')
    final_price = split_price[0]
    
    #rating=split_rating
    split_rating = rating.split(" ")
    final_rating = split_rating[0]
    
    
    #print(product_name.replace(",","|") + " \t " + final_price + " \t " +  final_rating + "\n")
    f.write(product_name + " " + final_price + " " + final_rating + "\n")
    

f.close()

df = pd.read_csv("product.csv")
df

                      Products_name                Pricing    Rating
0        Apple iPhone SE (Space Grey    32 GB) Rs.17999 4.4      NaN
1         Apple iPhone SE (Rose Gold    32 GB) Rs.17999 4.4      NaN
2            Apple iPhone SE (Silver    32 GB) Rs.17999 4.4      NaN
3               Apple iPhone 6 (Gold    32 GB) Rs.24999 4.4      NaN
4         Apple iPhone 6 (Space Grey    32 GB) Rs.24999 4.4      NaN
5              Apple iPhone SE (Gold    32 GB) Rs.17999 4.4      NaN
6    Apple iPhone 6s Plus (Rose Gold    32 GB) Rs.37999 4.4      NaN
7   Apple iPhone 6s Plus (Space Grey    32 GB) Rs.37999 4.5      NaN
8         Apple iPhone 6s Plus (Gold    32 GB) Rs.37999 4.4      NaN
9        Apple iPhone 6s (Space Grey    32 GB) Rs.34999 4.4      NaN
10        Apple iPhone X (Space Gray    64 GB) Rs.88999 4.6      NaN
11             Apple iPhone 7 (Black    32 GB) Rs.48999 4.5      NaN
12         Apple iPhone 7 (Rose Gold    32 GB) Rs.47999 4.5      NaN
13      Apple iPhone 6s Plus (Silver    32 GB) Rs.37999 4.5      NaN
14        Apple iPhone 6s (Rose Gold    32 GB) Rs.35999 4.4      NaN
15           Apple iPhone 6s (Silver    32 GB) Rs.35999 4.4      NaN
16              Apple iPhone 7 (Gold    32 GB) Rs.48999 4.5      NaN
17         Apple iPhone 8 Plus (Gold    64 GB) Rs.73999 4.6      NaN
18             Apple iPhone 6s (Gold    32 GB) Rs.35999 4.4      NaN
19   Apple iPhone 8 Plus (Space Grey    64 GB) Rs.73999 4.6      NaN
20             Apple iPhone 7 (Black   128 GB) Rs.54999 4.6      NaN
21         Apple iPhone 7 (Jet Black    32 GB) Rs.48999 4.5      NaN
22            Apple iPhone 7 (Silver    32 GB) Rs.48999 4.5      NaN
23              Apple iPhone 7 (Gold   128 GB) Rs.55999 4.5      NaN